### ISSUE TITLE
Plugin class EasyMart\PriceDecimal\Plugin\Pricing\Render\Amount doesn't exist

### ISSUE THREAD

**Issue by digitalgeneralist** [adarshkhatri/price-decimal-magento2#1]
I got this error after installing this extension.

1 exception(s):
Exception #0 (InvalidArgumentException): Plugin class EasyMart\PriceDecimal\Plugin\Pricing\Render\Amount doesn't exist

Exception #0 (InvalidArgumentException): Plugin class EasyMart\PriceDecimal\Plugin\Pricing\Render\Amount doesn't exist
#0 /var/www/html/vendor/magento/framework/Interception/PluginList/PluginList.php(151): Magento\Framework\Interception\PluginList\PluginList->_inheritPlugins('Magento\\Framewo...')
#1 /var/www/html/vendor/magento/framework/Interception/PluginList/PluginList.php(268): Magento\Framework\Interception\PluginList\PluginList->_inheritPlugins('WeltPixel\\Googl...')
#2 /var/www/html/generated/code/WeltPixel/GoogleCards/Model/Pricing/Render/Amount/Interceptor.php(945): Magento\Framework\Interception\PluginList\PluginList->getNext('WeltPixel\\Googl...', 'hasData')
#3 /var/www/html/vendor/magento/framework/View/Element/Template.php(182): WeltPixel\GoogleCards\Model\Pricing\Render\Amount\Interceptor->hasData('template')
#4 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(209): Magento\Framework\View\Element\Template->_construct()
#5 /var/www/html/vendor/magento/framework/View/Element/Template.php(154): Magento\Framework\View\Element\AbstractBlock->__construct(Object(Magento\Framework\View\Element\Template\Context), Array)
#6 /var/www/html/vendor/magento/framework/Pricing/Render/Amount.php(84): Magento\Framework\View\Element\Template->__construct(Object(Magento\Framework\View\Element\Template\Context), Array)
#7 /var/www/html/generated/code/WeltPixel/GoogleCards/Model/Pricing/Render/Amount/Interceptor.php(14): Magento\Framework\Pricing\Render\Amount->__construct(Object(Magento\Framework\View\Element\Template\Context), Object(Magento\Framework\Pricing\Amount\Base), Object(Magento\Directory\Model\PriceCurrency), Object(Magento\Framework\Pricing\Render\RendererPool), Object(Magento\Catalog\Model\Product\Interceptor), Object(Magento\ConfigurableProduct\Pricing\Price\FinalPrice), Array)
#8 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(116): WeltPixel\GoogleCards\Model\Pricing\Render\Amount\Interceptor->__construct(Object(Magento\Framework\View\Element\Template\Context), Object(Magento\Framework\Pricing\Amount\Base), Object(Magento\Directory\Model\PriceCurrency), Object(Magento\Framework\Pricing\Render\RendererPool), Object(Magento\Catalog\Model\Product\Interceptor), Object(Magento\ConfigurableProduct\Pricing\Price\FinalPrice), Array)

**Comment by adarshkhatri** [comment]
That's bit of unusual. Can you check if this file exist:

https://github.com/adarshkhatri/price-decimal-magento2/blob/master/EasyMart/PriceDecimal/Plugin/Pricing/Render/Amount.php

**Comment by digitalgeneralist** [comment]
yes it exists and permissions are ok ....
i had an 
bin/magento setup:upgrade
bin/magento setup:static-content:deploy -f de_DE en_US
bin/magento cache:clean

but the same problem

**Comment by digitalgeneralist** [comment]
I Use Magento 2.3.0

**Comment by adarshkhatri** [comment]
Can you try disabling `WeltPixel/GoogleCards` extension and give it a go. Looks like there is clash.

If it is the case then you can add `WeltPixel_GoogleCards` in sequence, that should work.

https://github.com/adarshkhatri/price-decimal-magento2/blob/master/EasyMart/PriceDecimal/etc/module.xml
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="EasyMart_PriceDecimal" setup_version="1.0.0">
		<sequence>
			<module name="Magento_Catalog"/>
			<module name="WeltPixel_GoogleCards"/>
		</sequence>
    </module>
</config>
```

**Comment by digitalgeneralist** [comment]
Nothing happens ....  
Now i saw that the EasyMart is not 
in generated/code

**Comment by digitalgeneralist** [comment]
I tried enable and disable module
Enable again then 

rm -rf generated/*
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento cache:flush

All Modules are generated but easyMart not

www-data@81ca20de0eb9:~/html$ ls -la generated/code/
total 72
drwxrwxr-x  18 www-data www-data 4096 Mar 27 08:09 .
drwxr-xr-x   4 www-data www-data 4096 Mar 27 08:09 ..
drwxrwxr-x   5 www-data www-data 4096 Mar 27 08:09 Amazon
drwxrwxr-x   4 www-data www-data 4096 Mar 27 08:09 BoostMyShop
drwxrwxr-x   3 www-data www-data 4096 Mar 27 08:09 Composer
drwxrwxr-x   3 www-data www-data 4096 Mar 27 08:09 Customweb
drwxrwxr-x   3 www-data www-data 4096 Mar 27 08:09 Dotdigitalgroup
drwxrwxr-x   5 www-data www-data 4096 Mar 27 08:09 Klarna
drwxrwxr-x   5 www-data www-data 4096 Mar 27 08:09 Magebees
drwxrwxr-x 124 www-data www-data 4096 Mar 27 08:09 Magento
drwxrwxr-x   4 www-data www-data 4096 Mar 27 08:09 Mageplaza
drwxrwxr-x   3 www-data www-data 4096 Mar 27 08:09 MSP
drwxrwxr-x  11 www-data www-data 4096 Mar 27 08:09 Stripeofficial
drwxrwxr-x   3 www-data www-data 4096 Mar 27 08:09 Symfony
drwxrwxr-x   3 www-data www-data 4096 Mar 27 08:09 Temando
drwxrwxr-x   5 www-data www-data 4096 Mar 27 08:09 Vertex
drwxrwxr-x  21 www-data www-data 4096 Mar 27 08:09 WeltPixel
drwxrwxr-x   3 www-data www-data 4096 Mar 27 08:09 WeSupply

**Comment by adarshkhatri** [comment]
Have you tried disabling `WeltPixel_GoogleCards`?

**Comment by digitalgeneralist** [comment]
Yes when i disable this Module comes still this here
(But normally a module should also be in generated/code  and  it is not. Thats the reason he could not find Amount class)

> 1 exception(s):
Exception #0 (InvalidArgumentException): Plugin class EasyMart\PriceDecimal\Plugin\Pricing\Render\Amount doesn't exist

Exception #0 (InvalidArgumentException): Plugin class EasyMart\PriceDecimal\Plugin\Pricing\Render\Amount doesn't exist
<pre>#1 Magento\Framework\Interception\PluginList\PluginList->getNext('Magento\Framewor...', 'hasData') called at [generated/code/Magento/Framework/Pricing/Render/Amount/Interceptor.php:932]
#2 Magento\Framework\Pricing\Render\Amount\Interceptor->hasData('template') called at [vendor/magento/framework/View/Element/Template.php:182]
#3 Magento\Framework\View\Element\Template->_construct() called at [vendor/magento/framework/View/Element/AbstractBlock.php:209]
#4 Magento\Framework\View\Element\AbstractBlock->__construct(&Magento\Framework\View\Element\Template\Context#0000000007c8a103000000007208872f#, array('price_render_han...' => 'catalog_product_...', 'use_link_for_as_...' => true, 'type' => 'Magento\Framewor...', 'is_product_list' => true, 'include_containe...' => true, 'display_minimal_...' => true, 'zone' => 'item_list', 'list_category_pa...' => true, 'module_name' => '', 'css_classes' => 'price-final_pric...', 'display_label' => &Magento\Framework\Phrase#0000000007c88046000000007208872f#, 'price_id' => 'product-price-79...', 'price_type' => 'finalPrice', 'schema' => false)) called at [vendor/magento/framework/View/Element/Template.php:154]
#5 Magento\Framework\View\Element\Template->__construct(&Magento\Framework\View\Element\Template\Context#0000000007c8a103000000007208872f#, array('price_render_han...' => 'catalog_product_...', 'use_link_for_as_...' => true, 'type' => 'Magento\Framewor...', 'is_product_list' => true, 'include_containe...' => true, 'display_minimal_...' => true, 'zone' => 'item_list', 'list_category_pa...' => true, 'module_name' => '', 'css_classes' => 'price-final_pric...', 'display_label' => &Magento\Framework\Phrase#0000000007c88046000000007208872f#, 'price_id' => 'product-price-79...', 'price_type' => 'finalPrice', 'schema' => false)) called at [vendor/magento/framework/Pricing/Render/Amount.php:84]
#6 Magento\Framework\Pricing\Render\Amount->__construct(&Magento\Framework\View\Element\Template\Context#0000000007c8a103000000007208872f#, &Magento\Framework\Pricing\Amount\Base#0000000007c88275000000007208872f#, &Magento\Directory\Model\PriceCurrency#0000000007c8ba2f000000007208872f#, &Magento\Framework\Pricing\Render\R

**Comment by adarshkhatri** [comment]
I cannot find the reason it's throwing that error. I can only guess it might be something to do with folder structure.

It should be:

`app => code => EasyMart => PriceDecimal`

**Comment by digitalgeneralist** [comment]
Thank you yes it was Problem in Path (EasyMart case-sensitive)

Thanks
